### ISSUE TITLE
Config file doesnt generate on docker install.

### ISSUE THREAD

**Issue by Releasement** [jbruws/acsim#4]
I am currently mailing a bomb to whoever is responsible for this error.

**Comment by jbruws** [comment]
Rebuilt the container on my laptop, and config file does generate. Here's output from a shell inside a running container:

```
root@adb0e071db47:/acsim# head data/config.yaml

---
# IP addresses and port used to serve the imageboard itself
server_ipv4: 127.0.0.1
server_ipv6: ::1
server_port: 8080

# If set to true, only binds to addresses specified above, otherwise binds to 0.0.0.0
bind_to_one_ip: false

root@adb0e071db47:/acsim# ls data
acsim.db  banlist.yaml	captcha  config.yaml  user_images
root@adb0e071db47:/acsim#
```

Docker still outputs `./setup.sh: 28: [[: not found` when building (*which I'll fix later*), but everything still seems to generate fine. It's probably an issue with the older version that current `acsim:latest` was generated from. Expect a new image sometime soon.

**Comment by Releasement** [comment]
Despite a new OS reinstall, redoing all of the steps, I've yet to generate a config file. I've tried the manual install and editing the setup file and have only gotten errors.

**Comment by jbruws** [comment]
> Despite a new OS reinstall, redoing all of the steps, I've yet to generate a config file. I've tried the manual install and editing the setup file and have only gotten errors.

Are any other files affected or is only the config missing? Also, could you share any of the error logs you got?

**Comment by Releasement** [comment]
I believe rust may be effected as well, whenever I tried to invoke or use anything related to rustup or its dependencies it would give an "incorrect directory" error. this could be because I installed all of the targets in the acsim directory but I'm not sure.

**Comment by Releasement** [comment]
Sorry, if not being specific enough. It always gave some type of "incorrect directory error" relating to "cargo install --path". Trying to replicate now.

**Comment by Releasement** [comment]
Error on my end. For future prosperity, don't cd when trying to mount or run this.
![artworks-000596536556-cwl06b-t500x500](https://github.com/jbruws/acsim/assets/165341859/9e2c8b70-ba98-4c85-a2c1-13a3f6c58866)
