### ISSUE TITLE
Very nice board...this has serious potential. 

### ISSUE THREAD

**Issue by ChessLogical** [jbruws/acsim#5]
Question, can you or someone make a couple different front ends? I would love something that resembles the traditional old school php boards :) 

Nice board! Ran into slight probs installing, chatgpt told me the things i needed to install, so install is easy , A+ for that! Would love to make this look like a traditional ib like tinyib or something. This board is amazing-- best ive ever seen.

i was on ubuntu 24.04 server - had to get off rust nightly build- that does NOT work for installing this, you have to get on the reg stable build of rust.  
rustup install stable
rustup default stable
rustup override set stable

After that, i had to install
sudo apt-get update
sudo apt-get install pkg-config
sudo apt-get install libmagic-dev
sudo apt-get install libssl-dev

And BAM - board is set up and works fine. Amazing to see a high performance board so easy to set up- best ive ever seen. Superior to vichan lynxchan jschan or https://usagi.reisen/  the golang ib,  Again, in comparison to others, VERY nice work... this one will be huge when people discover it.

**Comment by jbruws** [comment]
Thanks for the feedback!!

The next two months will be very busy for me, so I doubt there will be any commits here until August at least (the project is 90% done, anyways). You can also simply write your own frontend in the meantime - copy the default one and change html/css to your liking. Keep all handlebars blocks in place, though.

Regarding nightly Rust: I never used it, so I guess that installation caveat slipped past me. Will include that in README real quick
