### ISSUE TITLE
multiple boards?

### ISSUE THREAD

**Issue by ChessLogical** [jbruws/acsim#6]
How to deploy multiple boards? I see the one board in setup.sh and i try to ad new boards there, put them on separate line, it does not work. Thanks!

**Comment by jbruws** [comment]
Hey hey. `setup.sh` shouldn't really be edited at all; if you want to change the config, go to `data/config.yaml`, add new boards, and restart the server if it's running. That should do the trick

**Comment by ghost** [comment]
Thank you!

**Comment by ghost** [comment]
Got it, thanks much!
