### ISSUE TITLE
del

### ISSUE THREAD

**Issue by ghost** [jbruws/acsim#8]
Sry for dumb questions, this app is really nice and i would love to run it in production. Where does one enter the password for postgres setup? I see there is a closed issue with postgres db but that solution did not apply. I tried all sorts of different things that chatgpt says to and i can not get postgres  to work.  Not sure what im doing wrong, i started from scratch many times and try lots of variables and can not solve it.  Also testing the board,  i set  # Max amount of messages on one board hard_limit: 3 in order to see what happens when board limit is reached, nothing happens and posting keeps going as usual. Also as a general info,  i think it  often rejects posts even when i enter right captcha .  Thanks!!! (sqlite ubuntu 24.04 LTS)

**Comment by jbruws** [comment]
By default, acsim uses `trust` authentification metod - so, there *is no* Postgres password. If you want to add one, change auth method in `pg_hba.conf`, set the password for `postgres` user, and change the connection URL in acsim's `.env`

Overall, Postgres support is a bit wonky since I've mostly used SQLite during development. I'd suggest using Docker Compose for Postgres, since it actually works (I run it on production).

> posting keeps going as usual.

It does, but the oldest messages get deleted so the total amount of messages doesn't go over the limit.

> reject posts even when i enter right captcha

Tested that out also, the captcha seems to work as intended. The server can't really fail the verification; it just compares hash of text on captcha and hash of the poster's answer. Lowercase "l", the number one ("1") and uppercase "I" all look similiar in captchas, so that might be the culprit.

**Comment by ghost** [comment]
okay thanks ill look into it more and provide relevant data. I would like to get postgres going, the setup.sh asks for the password I tried variables, set the config to md5, you name it i tried it, and since there was another person with same hardships, it is safe to say postgres could use a bit of simplification- at least for non postgres morons like me! Truly awesome board you made tho, I hope you keep on it- i believe its the best ib out there for real!! Thanks for your time and the awesome code!!!

**Comment by jbruws** [comment]
`setup.sh` asks you for the **dashboard password**, which allows you to moderate the IB. Go to `localhost:8080/dashboard`. There is no password for the *database* by default

**Comment by ghost** [comment]
mine asks for the dashboard pass then db pass.  ububtu 2404

**Comment by jbruws** [comment]
It might be the database config then. What is the last message the script prints before prompting you for a Postgres password?

**Comment by ghost** [comment]
i feel like im being gaslit lol.. i do not lie when i mentioned the probs. I am shifting focus for now, and have been focusing on https://github.com/ChessLogical/dream-/tree/main . It is insane small and simple ib in rust its working except the file uploads. (sqlite3 3 for now, i also have a version working with SLED db but i will get the sqlite3 one working first). Your board is superior to anything i could ever make, i will admit that, but in today's age of chatgpt i would rather code everything myself using chatgpt. I am new to rust and am fascinated by rust so am making small but awesome rust apps. If i could get my dream app working i will actually run it on a chess website. (if you could help fix it that would be awesome lol). Anyways, give me  while, im focused on making my own, but i will make a user feedback video for you for user feedback, and the video will show in detail the proof of the probs i mentioned. Kind of like im part of a focus group lol. I am not good enough to help you code but i will be more than happy to help test your app and give feedback as a new user of your app. And although ACSIM is superior to anything i could make, i think its best to stick with extremely simple apps so i can fix and improve them easily in the future. Like dream for example is only about 300 lines of the main.rs and its actually a fully functional db. Pagination, reply functions are working great. My idea is to keep it in sqlite3 to easily be able to use sqlite3 editor as an admin. So one tiny main.rs file for the entire app, and to me that is perfectly how a rust app should be! Anyways give me a few hours ive been up for 18 hours trying to make dream- i will make a nice feedback vid for ya and upload it to yt, then i can delete the vid when u want. Thanks for the constant feedback tho, you are doing an awesome job at being a good person on github and you make an awesome app!!

**Comment by ghost** [comment]
Update-- i got my 300 line ib working half way decent. ACSIM is awesome and the best board out there, in order to learn rust i have to run simple boards closer to my level, so will just run my own i guess. That being said tho, seems to me ACSIM is the best board out there by far, if you keep at it i predict it will become very popular and overtake existing boards. 
Some suggestions- the default css design is radically different than what ppl expect from an imageboard and could hold back your board. Post form  or link to post form on top, messages under it is the traditional way on tinyib tinyboard vichan lynxchan jschan and others. It is just easier to navigate that way. While thinking outside the box is best for sure, in a case like this- start by using the traditional ib layout then be more subtle about slowly thinking outside the box if needed. But make your board look like the imageboard that people expect and it will thrive. 
Next, having only one db method is best. Stick to one db, develop it, battle test then battle harden it, and you have an awesome app. Double the db just cuts the progress in half, if people all use the same db the dev and battle testing is much faster. Postgres is superior, because it allows easy admin area and things like that. But there are rust made db now, even one like Sled that requires zero setup. A modern more functional than Sled rust made db would set your board apart from others tho. Modern databases coded in rust and for rust are the way to go. 
One MAJOR problem with boards is setup. LynxChan and JS chan are easy to set up for ppl who can enter the right dep setups and configure the server a bit, but i bet 80 or more percent of ppl can not even properly do all that and set up the board. Making an install script that reliably sets up the board goes miles with ppl interested in setting up an ib. 
I honestly believe your board can become the top board out there, the board that everyone wants to run. And unlike the people toiling with updating the node js lynxchan or jschan boards on the daily,  well coded rust ib can run for about 50 years. A profound advantage. Ppl can sense if you are serious or not... you have the talent and skills. 

People of earth need a good reliable ib- yours fits the bill if you are willing to keep at it.

**Comment by ghost** [comment]
within a day or 2 i will make a vid showing some of the things i mentioned while setting up acsim. i will post the link here to the vid, then delete the vid after u see it.  edit... by the way https://usagi.reisen/ is prolly the best non js board out there, it is made with go. Rust is superior to Go, and i would imagine yours could overtake usagi with minimal changes.

**Comment by ghost** [comment]
update!!! OMG i did not realize that for postgre one does not have to set up a db, it does it all for you! It asks for 3 things and does everything on its own. THAT is amazing easy install for ppl, maybe explain in readme that that is all ppl have to do!!! I was screwing it up by making my own database!!! Sorry about that, totally my fault!!!

**Comment by ghost** [comment]
also if you wanna hear something funny, i was using Rocket and ran into a bug with it that made my ib say some files are too big, and then next post it let me post a larger file. I spent 4 days trying to trace the problem, chat gpt gave me a zillion "fixes", made me a zillion scripts to try and trace the problem, then i find out that its a common issue and to use actix like you do instead of rocket. So now im screwed, all my web apps made with rocket have to be dumped, i have to switch to actix for all apps in order to learn. It is funny and stupid at the same time... i wasted 4 verly long days straight trying to figure it out then finally realized to switch to actix. Paying my dues a bit while learning rust lol.

**Comment by ghost** [comment]
![Screenshot 2024-05-27 045251](https://github.com/jbruws/acsim/assets/169053333/29c7ad1f-7009-470a-b90c-a4aaa9f117f6)

I guess there was probs with postgres... its okay tho i will be busy for about 2 weeks making my own ib. Its funny i know mine sux, but im trying to make an ib for production , then compare it to yours. Yours will likely be better and i will end up using your ib  for production, Im just making one for fun and to learn a bit about web coding with rust.

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=lFtGAps0UcU   I always run into probs with the captcha. Also, to delete a post it has to be reported, and to report a post even the mod has to enter captcha, which is problematic.

**Comment by ghost** [comment]
check out my Adelia repo! Its worth downloading and running. Crazy small codebase, will be improving it for bout 2 weeks at least.

**Comment by ghost** [comment]
Update--- Adelia repo now has almost every feature of vichan, and its one rust file less than 300 lines.
